version: '3.7'

services:
  app:
    volumes:
    - ./:/app
    - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    #env_file:
    #  - ./.env
    networks: 
      - expressjs
  mongo:
    volumes:
      - mongo-db:/data/db
    ports:
      - "27017:27017"
    networks: 
      - expressjs
networks:
  expressjs:
    driver: bridge