version: '3.7'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
     - "3000:3000"
    volumes:
    - ./:/app
    - /app/node_modules
    environment:
      - PORT=3000
    #env_file:
    #  - ./.env
    networks: 
      - expressjs

networks:
  expressjs:
    driver: bridge
